package main

type tokenKind string

const (
	SPECIALCHARACTER = "SPECIALCHARACTER"
	STRING = "STRING"
	BAREWORD = "BAREWORD"
	EQUAL = "EQUAL"
	NOTEQUAL = "NOTEQUAL"
	AND = "AND"
	OR = "OR"
	ENDOFINPUT = "ENDOFINPUT"
	CLOSEPARENTHESIS = "CLOSEPARENTHESIS"
	OPENPARENTHESIS = "OPENPARENTHESIS"
	FLOAT = "FLOAT"
	GREATERTHAN = "GREATERTHAN"
	LESSTHAN = "LESSTHAN"
	GREATERTHANANDEQUAL = "GREATERTHANANDEQUAL"
	LESSTHANANDEQUAL = "LESSTHANANDEQUAL"
	INTEGER = "INTEGER"
)

func GetTokenKind(kind tokenKind) string {
	switch  kind {
	case "SPECIALCHARACTER":
		return "SPECIALCHARACTER"

	case "STRING":
		return "STRING"

	case "EQUAL":
		return "EQUAL"

	case "BAREWORD":
		return "BAREWORD"
	}
	return "Invalid Token"
}